#!/usr/bin/bash

if [ ! -d "src/main/kotlin/adventofcode/aoc$1" ]; then
    mkdir -p src/main/kotlin/adventofcode/aoc$1
fi
sed -e "s/{yyyy}/$1/g" -e "s/{dd}/$2/g" src/main/resources/template.kt > src/main/kotlin/adventofcode/aoc$1/Day$2.kt